% Load all data

load('aca_iti.mat')
load('aca_task.mat')
load('bla_iti.mat')
load('bla_task.mat')
load('ca1_iti.mat')
load('ca1_task.mat')
load('ca2_iti.mat')
load('ca3_iti.mat')
load('ca3_task.mat')
load('dg_iti.mat')
load('dg_task.mat')
load('ila_iti.mat')
load('ila_task.mat')
load('orb_iti.mat')
load('orb_task.mat')
load('pl_iti.mat')
load('pl_task.mat')